# Workflow names are optional, but should be provided.
# They are displayed on GitHub when the action is run.
name: Hello world

# The `on` property configures the events that will trigger the workflow.
# In our case we want it to run when the `pull_request` event is triggered.
# In short, that means that the workflow will run when a pull request is
# either opened or updated (but not renamed or labeled – code needs to
# be changed).
on:
  - pull_request

# Jobs are what actually do the work. We can add as many jobs as we want.
# These will be run in parallel.
jobs:
  hello_world_job:
    # As with workflow names (and even step names), job names are not
    # strictly required, but they are good practice.
    name: Hello world

    # There are many virtual machines we can run our jobs on. The most
    # common one is `ubuntu-latest`.
    runs-on: ubuntu-latest

    # Each job can have multiple steps. These will be run in sequence.
    steps:
      - name: Hello world action step
        run: echo "Hello 🌏!"
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
      # To reference external workflows, we use the `uses` keyword.
      # The thing after the `@` is the version of the workflow, and is a Git tag.
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
  vitebuild: 
    name: vite-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Vite build
        run: npm run build
  vite-run: 
    name: vite-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Vite run
        run: npm run test
  lint: 
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: eslint
        run: npm run lint:check
  format: 
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: formatcheck
        run: npm run format:check
